server:
  port: 9966
  servlet:
    context-path: /edu
spring:
  datasource:
    url: jdbc:mysql://47.98.162.118:3306/edu?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Mxker5120
    driver-class-name: com.mysql.cj.jdbc.Driver
  druid:
    # 初始化配置
    initial-size: 2
    # 最小连接数
    min-idle: 2
    # 最大连接数
    max-active: 10
    # 获取连接超时时间
    max-wait: 5000
    # 连接有效性检测时间
    time-between-eviction-runs-millis: 90000
    # 最大空闲时间
    min-evictable-idle-time-millis: 1800000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    validation-query: select 1
  redis:
    #数据库索引
    database: 1
    host: 47.98.162.118
    port: 6379
    password:
    #连接超时时间
    timeout: 5000
